Advanced hook
ooyala/android-sample-apps pull request #186
Opened 2017-05-29 12:15 UTC by sgupta3112

Hi @rcvrgs , 

I have pushed AdvancedPlayback Sample App modified code.

Please review it and let me know if any changes required. 

Thanks 
Shivam Gupta

2017-06-21 23:09 UTC, brol1dev requested changes

2017-06-21 23:09 UTC, brol1dev commented on AdvancedPlaybackSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		if(TAG.toString().equalsIgnoreCase("class com.ooyala.sample.players.InsertAdPlayerActivity"))
Remove `.toString()`

2017-06-21 23:09 UTC, brol1dev commented on AdvancedPlaybackSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +			if(TAG.toString().equalsIgnoreCase("class com.ooyala.sample.players.ProgrammaticVolumePlayerActivity"))
Remove `.toString()`

2017-06-21 23:09 UTC, rcvrgs commented on AdvancedPlaybackSampleApp/app/src/main/java/com/ooyala/sample/players/NotificationsPlayerActivity.java
> +
Check this `update` method, you are not checking if you have rights to write to the SD card so sometimes it may fail.

2017-06-22 07:45 UTC, sgupta3112 commented on AdvancedPlaybackSampleApp/app/src/main/java/com/ooyala/sample/players/NotificationsPlayerActivity.java
> +
Yes, This is working file I checked this on Samsung Note 5 + Android 7.

2017-06-22 07:45 UTC, sgupta3112 commented on AdvancedPlaybackSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +			if(TAG.toString().equalsIgnoreCase("class com.ooyala.sample.players.ProgrammaticVolumePlayerActivity"))
Done.

2017-06-22 07:45 UTC, sgupta3112 commented on AdvancedPlaybackSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		if(TAG.toString().equalsIgnoreCase("class com.ooyala.sample.players.InsertAdPlayerActivity"))
Done.

2017-08-01 19:47 UTC, merged