added AbstarctHookActivity for External file permission access
ooyala/android-sample-apps pull request #189
Opened 2017-05-31 06:55 UTC by sgupta3112

Hi @rcvrgs , 

Please review the code and let me know if any changes required. 

Thanks
Shivam Gupta

2017-05-31 23:56 UTC, brol1dev requested changes
Additional comments:
* Use 2 or 4 tab/spaces when indenting code.
* Did the app work properly? Did you test going back to the list Activity to see if playback was paused automatically?
* The `AbstractHookActivity` must be modified accordingly depending on the sample app. I see you modified it here a bit, but you kept the child class untouched. Meaning there is duplicated code in some cases. You should refactor this code when you are making the changes, since you are introducing new code implying you know what you are doing and you have the chance to improve our code.

Please update the code and I'll review once more.

2017-05-31 23:56 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> + * Created by FTT on 30/05/17.
Remove the author comment

2017-05-31 23:56 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		Log.d(TAG, "Notification Received: " + arg1 + " - state: " + player.getState());
reuse the text variable since you're using the exact same string literal.

2017-05-31 23:56 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		String text="Notification Received: " + arg1 + " - state: " + player.getState();
use spaces here to define the variable, e.g. `String text = "Notification ..."`

2017-05-31 23:56 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/PulsePlayerActivity.java
> +	private OoyalaSkinLayoutController playerSkinLayoutController;
Why are you defining this variable if it is already part of the parent? Either use this one or the one in the parent Activity.

2017-05-31 23:56 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected void setPlayerLayoutController(OoyalaSkinLayoutController playerSkinLayoutController) {
why do you define this method? You can access the `playerSkinLayoutController` member of this class from the child class

2017-05-31 23:56 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		if (player != null) {
use `null != player`, this is just a typo safety mechanism

2017-05-31 23:56 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		if (player != null) {
use it everywhere you check for `null` values

2017-05-31 23:56 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	final String LOG_TAG = this.getClass().toString();
Why do you define both `TAG` and `LOG_TAG`? They have the same purpose

2017-05-31 23:56 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/PulsePlayerActivity.java
> +	final String PCODE  = "tlM2k6i2-WrXX1DE_b8zfhui_eQN";
You have these pcode and Domain both defined here and in the parent class.

2017-06-01 07:18 UTC, sgupta3112 commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/PulsePlayerActivity.java
> +	private OoyalaSkinLayoutController playerSkinLayoutController;
Made the changes. Defined in parent class.

2017-06-01 07:18 UTC, sgupta3112 commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/PulsePlayerActivity.java
> +	final String PCODE  = "tlM2k6i2-WrXX1DE_b8zfhui_eQN";
Done the changes.

2017-06-01 07:18 UTC, sgupta3112 commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		Log.d(TAG, "Notification Received: " + arg1 + " - state: " + player.getState());
Done.

2017-06-01 07:19 UTC, sgupta3112 commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		String text="Notification Received: " + arg1 + " - state: " + player.getState();
Done

2017-06-01 07:19 UTC, sgupta3112 commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		if (player != null) {
done the changes.

2017-06-01 07:20 UTC, sgupta3112 commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected void setPlayerLayoutController(OoyalaSkinLayoutController playerSkinLayoutController) {
Yes. Now we have defined in parent class in using that in child class as well. removed this method.

2017-06-01 07:20 UTC, sgupta3112 commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	final String LOG_TAG = this.getClass().toString();
Removed LOG_TAG.

2017-06-01 07:20 UTC, sgupta3112 commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> + * Created by FTT on 30/05/17.
Removed.

2017-06-01 08:03 UTC, sgupta3112 commented
Hi @rcvrgs ,

Thanks for all valuable suggestion. I'll try to maintain the decorum of code henceforth. 

Now, I have done all the changes in sample app code. 

Please review the code once again.

Thanks, 
Shivam Gupta

2017-06-06 06:50 UTC, brol1dev requested changes
Requested more changes

2017-06-06 06:50 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		super.onCreate(savedInstanceState);
configure your IDE to use less space for indentation, as I see it your adding like 8 spaces. The standard is 2 or 4.

2017-06-06 06:50 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		if (playerSkinLayoutController != null) {
when I asked to change null, i meant for all cases when you encounter them, you just changed it for when you ask for the player. Whenever you check for null use it as `null != variable`

2017-06-06 06:50 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/PulsePlayerActivity.java
> +
Remove this big spacing, if you want to have spacing it's ok but just add 1 line. In this case there's 2 lines spacing.

2017-06-06 06:50 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/PulsePlayerActivity.java
> +
Look in the code where else you are doing it.

2017-06-06 06:50 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +			return;
In this case you wont save the Error log in the SD, is that ok expected by you?

2017-06-06 06:50 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		embedCode = getIntent().getExtras().getString("embed_code");
do you ever use this embedCode? I think you take the embed code from the `getVideoItem` method.

2017-06-07 00:40 UTC, brol1dev requested changes
added more feedback

2017-06-07 00:40 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +  final String PCODE = "tlM2k6i2-WrXX1DE_b8zfhui_eQN";
Move this `PCODE` and `DOMAIN` to the PulsePlayerActivity, you don't use them here.

2017-06-07 00:40 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +  public VideoItem getVideoItem() {
move `getVideoItem()` method to PulsePlayerActivity.

2017-06-07 00:40 UTC, rcvrgs commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/PulsePlayerActivity.java
> +	final VideoItem videoItem = getVideoItem();
This is causing the player to be instantiated twice, the reason I added the `asked` parameter is to check if we already asked for permissions, we should do nothing if we haven't. Here's an example: https://github.com/ooyala/android-sample-apps/blob/dev/FreewheelSampleApp/app/src/main/java/com/ooyala/sample/players/PreconfiguredFreewheelPlayerActivity.java#L42

2017-06-08 05:15 UTC, sgupta3112 commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +  final String PCODE = "tlM2k6i2-WrXX1DE_b8zfhui_eQN";
That has been done. But I waana know that in future if we add another player activity class that time we have to add PCODE and EmbedCode again in that class as well. If we are putting it in parent class then that will be fine. Let me know your view here.

2017-06-08 05:15 UTC, sgupta3112 commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +  public VideoItem getVideoItem() {
That also has been done.

2017-06-08 05:30 UTC, sgupta3112 commented on PulseSampleApp/app/src/main/java/com/ooyala/sample/players/PulsePlayerActivity.java
> +	final VideoItem videoItem = getVideoItem();
Yeah exactly. Done that changes. I missed that.

2017-06-08 22:40 UTC, brol1dev approved these changes
Looks good now. One more question, have you tested this new code with devices with Android older than version 23? We want to verify it still works. Can you confirm that please?

2017-06-09 04:48 UTC, sgupta3112 commented
Hi @rcvrgs , 

Tested sample app on Android 4.4.2 observed that it is working fine. We are good to go.

2017-06-12 20:02 UTC, merged