Skin hook
ooyala/android-sample-apps pull request #190
Opened 2017-05-31 07:07 UTC by sgupta3112

Hi @Eric, 

We have modified All activity file of SkinSampleApp. 

Please review the code and let me know if any changes are required. 

Thanks, 
Shivam Gupta

2017-06-12 21:31 UTC, brol1dev requested changes

2017-06-12 21:31 UTC, rcvrgs commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/CustomConfiguredIMAPlayerActivity.java
> +    PlayerDomain domain1 = new PlayerDomain(domain);
call the variable `playerDomain` instead of `domain1`

2017-06-12 21:31 UTC, rcvrgs commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/OoyalaSkinPlayerActivity.java
> +			PlayerDomain domain1 = new PlayerDomain(domain);
rename to `playerDomain`

2017-06-12 21:31 UTC, rcvrgs commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/PreconfiguredFreewheelPlayerActivity.java
> +			PlayerDomain domain1 = new PlayerDomain(domain);
rename to `playerDomain`

2017-06-12 21:31 UTC, rcvrgs commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/PreconfiguredIMAPlayerActivity.java
> +			PlayerDomain domain1 = new PlayerDomain(domain);
rename to `playerDomain`

2017-06-12 21:31 UTC, rcvrgs commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/PreconfiguredIMAPlayerActivity.java
> +
Remove all these unnecessary space

2017-06-13 04:57 UTC, sgupta3112 commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/OoyalaSkinPlayerActivity.java
> +			PlayerDomain domain1 = new PlayerDomain(domain);
Done

2017-06-13 04:58 UTC, sgupta3112 commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/PreconfiguredFreewheelPlayerActivity.java
> +			PlayerDomain domain1 = new PlayerDomain(domain);
Done

2017-06-13 04:58 UTC, sgupta3112 commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/PreconfiguredIMAPlayerActivity.java
> +			PlayerDomain domain1 = new PlayerDomain(domain);
Done

2017-06-13 04:58 UTC, sgupta3112 commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/PreconfiguredIMAPlayerActivity.java
> +
Done.

2017-06-13 19:06 UTC, brol1dev requested changes

2017-06-13 19:06 UTC, rcvrgs commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected OoyalaSkinLayoutController controller;
remove this variable, you already have another of the same type (`playerLayoutController`).

2017-06-13 19:06 UTC, rcvrgs commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	//protected OptimizedOoyalaPlayerLayoutController playerLayoutController;
remove this commented line

2017-06-13 19:06 UTC, rcvrgs commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/CustomConfiguredFreewheelPlayerActivity.java
> +			controller = new OoyalaSkinLayoutController(getApplication(), skinLayout, player, skinOptions);
use `playerLayoutController` instead of `controller`

2017-06-13 19:06 UTC, rcvrgs commented on OoyalaSkinSampleApp/app/src/main/java/com/ooyala/sample/players/PreconfiguredIMAPlayerActivity.java
> +
i don't see it changed.

2017-06-21 23:17 UTC, brol1dev approved these changes

2017-06-21 23:17 UTC, merged