Npaw Sample App Modified code for external storage aceess
ooyala/android-sample-apps pull request #191
Opened 2017-06-09 06:15 UTC by sgupta3112

Hi @rcvrgs , 

Here I have added AbstractHookActivity class in player package. Also we have added permission in manifest file as well. 

Tested sample app on Android 4.4.2 and Android 6.

2017-06-12 22:00 UTC, brol1dev requested changes

2017-06-12 22:00 UTC, rcvrgs commented on NPAWSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		log.writeToSdcardLog(text);
you missed to use the `writePermission` variable here

2017-06-12 22:00 UTC, rcvrgs commented on NPAWSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected PluginOoyala pluginOoyala;
I would move `PluginOoyala` to `NPAWDefaultPlayerActivity`.

2017-06-12 22:00 UTC, rcvrgs commented on NPAWSampleApp/app/src/main/java/com/ooyala/sample/players/NPAWDefaultPlayerActivity.java
> -      pluginOoyala.stopMonitoring();
you got rid of this code to stop and resume `pluginOoyala`, add it again.

2017-06-19 09:53 UTC, sgupta3112 commented on NPAWSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected PluginOoyala pluginOoyala;
Moved to NPAWDefaultPlayerActivity.

2017-06-19 09:54 UTC, sgupta3112 commented on NPAWSampleApp/app/src/main/java/com/ooyala/sample/players/NPAWDefaultPlayerActivity.java
> -      pluginOoyala.stopMonitoring();
Added this in NPAWDefaultPlayerActivity.java file

2017-06-21 23:20 UTC, brol1dev requested changes

2017-06-21 23:20 UTC, rcvrgs commented on NPAWSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		log.writeToSdcardLog(text);
you haven't updated this.

2017-06-21 23:20 UTC, rcvrgs commented on NPAWSampleApp/app/src/main/java/com/ooyala/sample/players/NPAWDefaultPlayerActivity.java
> -    pluginOoyala.resumeMonitoring();
i don't see you're resumingMonitoring elsewhere, and you removed this. I think the implementation is broken. Make sure to know when to start, pause, resume and stop monitoring.

2017-06-22 09:18 UTC, sgupta3112 commented on NPAWSampleApp/app/src/main/java/com/ooyala/sample/players/NPAWDefaultPlayerActivity.java
> -    pluginOoyala.resumeMonitoring();
Yes, We have added this.

2017-06-22 09:18 UTC, sgupta3112 commented on NPAWSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +		log.writeToSdcardLog(text);
Updated.

2017-08-01 19:43 UTC, brol1dev approved these changes

2017-08-01 19:43 UTC, merged