added AbstractHookActivity.java file and updated remaining file accor…
ooyala/android-sample-apps pull request #193
Opened 2017-06-20 11:00 UTC by sgupta3112

Hi @rcvrgs , 

I have raise this PR regarding OptionSample App. 

Please review the code and let me know if any changes required. 

Shivam Gupta

2017-06-21 23:26 UTC, brol1dev requested changes

2017-06-21 23:26 UTC, rcvrgs commented on OptionsSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected String EMBEDCODE;
rename to `EMBED_CODE`

2017-06-21 23:26 UTC, rcvrgs commented on OptionsSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected OptimizedOoyalaPlayerLayoutController playerLayoutController;
use better variable names, call this one `optimizedPlayerLayoutController`

2017-06-21 23:26 UTC, rcvrgs commented on OptionsSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected OoyalaPlayerLayoutController ooyalaplayerLayoutController;
call this one `playerLayoutController`

2017-06-22 08:04 UTC, sgupta3112 commented on OptionsSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected OptimizedOoyalaPlayerLayoutController playerLayoutController;
Done.

2017-06-22 08:04 UTC, sgupta3112 commented on OptionsSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected OoyalaPlayerLayoutController ooyalaplayerLayoutController;
Done.

2017-06-22 08:04 UTC, sgupta3112 commented on OptionsSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected String EMBEDCODE;
Done.

2017-08-01 18:08 UTC, rcvrgs commented on OptionsSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected OoyalaPlayerLayoutController playerLayoutController;
What happens if the activity owning the `playerLayoutController` instance calls `onStop` or `onPause`? It doesn't look like the video will be paused and resumed as you do for `optimizedOoyalaPlayerLayoutController`. Test those use cases and change if there's an issue.

2017-08-07 06:39 UTC, sgupta3112 commented on OptionsSampleApp/app/src/main/java/com/ooyala/sample/players/AbstractHookActivity.java
> +	protected OoyalaPlayerLayoutController playerLayoutController;
Changes Done, Please review.

2017-08-08 00:09 UTC, merged