[PLAYER-2070] Refactored sample to kotlin, added videos from test data
ooyala/android-sample-apps pull request #229
Opened 2017-10-29 10:56 UTC by IvanSakharovskii

2017-10-30 10:48 UTC, atopilskii commented on VRSampleApp/app/src/main/java/com/ooyala/sample/screen/VideoFragment.kt
> +      Log.d(TAG, text)
Is it good idea to extract variable for this text?

2017-10-30 10:51 UTC, atopilskii approved these changes

2017-10-30 13:46 UTC, AlinaVoronkovaEpam requested changes
I'm not sure if we should keep two versions of VR sample app for Java and Kotlin or not. Let's ask Eric. Anyway the sample looks fine for me.

2017-10-31 15:57 UTC, akshaydch11 commented
@AlinaVoronkovaEpam  I think short answer is yes we want both java and kotlin versions. We can discuss it review meeting sometime.

2017-11-03 11:01 UTC, AlinaVoronkovaEpam approved these changes

2017-11-03 11:01 UTC, merged