[PLAYER-2375]
ooyala/android-sample-apps pull request #291
Opened 2018-02-07 10:39 UTC by atopilskii

2018-02-09 13:53 UTC, AlinaVoronkovaEpam requested changes

2018-02-09 13:53 UTC, AlinaVoronkovaEpam commented on ChromecastV3SampleApp/app/src/main/java/com/ooyala/chromecastv3sampleapp/ChromecastPlayerActivity.java
> +  private String embedCode2;
Please name it according to the purpose of usage

2018-02-09 13:53 UTC, AlinaVoronkovaEpam commented on ChromecastV3SampleApp/app/src/main/java/com/ooyala/chromecastv3sampleapp/ChromecastListActivity.java
> +    intent.putExtra("embedcode2", videoList[position].embedCode2);
`embedcode2` - please name it according to the purpose of usage

2018-02-09 13:53 UTC, AlinaVoronkovaEpam commented on ChromecastSampleApp/app/build.gradle
indents

2018-02-09 13:53 UTC, AlinaVoronkovaEpam commented on ChromecastV3SampleApp/app/build.gradle
> +}
Please check the indents

2018-02-09 13:53 UTC, AlinaVoronkovaEpam commented on ChromecastV3SampleApp/app/src/main/java/com/ooyala/chromecastv3sampleapp/ChromecastPlayerActivity.java
> +  private final String ACCOUNT_ID = "accountID";
Why don't you move `APIKEY `, `SECRET ` and `ACCOUNT_ID ` on to ChromecastPlayerSelectionOption?
It would be pretty easy to add new assets with different params I mentioned above.

2018-02-09 13:53 UTC, AlinaVoronkovaEpam commented on ChromecastV3SampleApp/app/src/main/java/com/ooyala/chromecastv3sampleapp/cast/CastManager.java
> +  }
Could you please add check on null here? What if `castManager ` is already exists?

2018-02-09 13:53 UTC, AlinaVoronkovaEpam commented on ChromecastV3SampleApp/app/src/main/java/com/ooyala/chromecastv3sampleapp/cast/CastManager.java
> +        ((ViewGroup) castView.getParent()).removeView(castView);
Create a variable `ViewGroup smh = castView.getParent();` and then check on null and `removeView`

2018-02-09 13:53 UTC, AlinaVoronkovaEpam commented on ChromecastV3SampleApp/app/src/main/java/com/ooyala/chromecastv3sampleapp/cast/CastManager.java
> +public class CastManager implements CastManagerInterface, CastSessionListener.ConnectStatusListener {
Is it possible to keep `CastManager` as a part of the sdk?

2018-02-09 14:25 UTC, atopilskii commented on ChromecastV3SampleApp/app/src/main/java/com/ooyala/chromecastv3sampleapp/ChromecastPlayerActivity.java
> +  private final String ACCOUNT_ID = "accountID";
As I know, we have the same task in Jira. I think it is more correctly do this changes as part of those task, not here.

2018-02-22 12:57 UTC, AlinaVoronkovaEpam approved these changes

2018-02-22 12:58 UTC, merged