Player 2375
ooyala/android-sample-apps pull request #298
Opened 2018-02-26 20:06 UTC by atopilskii

Delete old CastSampleApp v2 and rename new CastV3SampleApp to CastSampleApp

2018-02-27 01:47 UTC, brol1dev requested changes

2018-02-27 01:47 UTC, brol1dev commented on ChromecastSampleApp/app/build.gradle
> +    from new File(vendorDir, 'Ooyala/OoyalaSDK-Android/OoyalaSDK.jar')
we should be using .aar now, right?

2018-02-27 01:47 UTC, brol1dev commented on ChromecastSampleApp/app/src/main/java/com/ooyala/sample/CastOptionsProvider.java
> + * Don't delete this class. It is used to provide google cast options by manifest.
You can safely remove the `Don't delete this class` comment :) Just explain what it's used for.

2018-02-27 07:57 UTC, atopilskii commented on ChromecastSampleApp/app/build.gradle
> +    from new File(vendorDir, 'Ooyala/OoyalaSDK-Android/OoyalaSDK.jar')
done

2018-02-27 07:57 UTC, atopilskii commented on ChromecastSampleApp/app/src/main/java/com/ooyala/sample/CastOptionsProvider.java
> + * Don't delete this class. It is used to provide google cast options by manifest.
Done

2018-03-09 00:19 UTC, rcvrgs commented
Can you update this PR's branch with the latest changes from `dev`?

2018-03-13 17:02 UTC, atopilskii commented
done

2018-03-20 02:38 UTC, akshaydch11 approved these changes

2018-03-20 05:33 UTC, merged