custom activiy to pass apikey and secet key
ooyala/android-sample-apps pull request #333
Opened 2018-05-08 15:50 UTC by sndy35

Please review the custom activity added to pass the asset details from app

2018-05-17 00:11 UTC, brol1dev requested changes

2018-05-17 00:11 UTC, brol1dev commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/lists/ContentProtectionListActivity.java
> +    selectionMap.put("OPT HLS", new PlayerSelectionOption("NjZ3B3ZDE6hN_sIoXotGDlI1s2cDLUwH", "BjcWYyOu1KK2DiKOkF41Z2k0X57l", "http://www.ooyala.com", OoyalaPlayerTokenPlayerActivity.class) );
are all of these cases part of your QA test cases?

2018-05-17 00:11 UTC, brol1dev commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/players/CustomActivity.java
> + * This activity illustrates how we can dynamically add and play video using Skin SDK by adding the embed code and PCode.
This app doesn't use the Skin SDK, adding this comment can confuse customers. Remove the mention of SkinSDK please.

2018-05-17 00:11 UTC, brol1dev commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/players/CustomActivity.java
> +  * You can Select OoyalaDefault for BasicSkinPlayback also use it for playing Ooyala and VAST advertisements.
Don't understand this comment, where is BasicSkinPlayback? and what do you mean by OoyalaDefault.

Also there are no VAST ads in this app.

2018-05-17 00:11 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/players/CustomActivity.java
> +  * Also You can select Assets with GoogleIMA and Freewheel by selecting the respective players.
Remove this comment.

2018-05-17 00:11 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/players/CustomActivity.java
> +         *  * @author skumar
remove author

2018-05-17 00:11 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/players/CustomActivity.java
> +        import android.app.Activity;
remove the extra space at the beginning of all of the imports.

2018-05-17 00:11 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/complete/MainActivity.java
> + *
remove these extra lines in the comment if there are no comments.

2018-05-17 00:11 UTC, rcvrgs commented on ContentProtectionSampleApp/app/build.gradle
> +
remove all the extra spaces added in this file

2018-05-17 00:11 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/players/CustomActivity.java
> +  private EditText apikeyEditText;
use camel case for `apiKey` too

2018-05-17 00:11 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/players/CustomActivity.java
> +  private EditText accountidEditText;
use camelCase for `accountId`

2018-05-17 00:11 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/players/OoyalaPlayerTokenPlayerActivity.java
> +  private String APIKEY = "BjcWYyOu1KK2DiKOkF41Z2k0X57l.0I-V4";
remove api key and secret values, these are supposed to be secret. Are this from a test account? If not you'll need to completely remove them from GIT.

2018-05-17 00:11 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/players/OoyalaPlayerTokenPlayerActivity.java
> +      if(AUTOPLAY)
add extra braces for this if, it doesn't matter if it's only one line.

2018-05-17 00:11 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/res/values/strings.xml
> +        <string name="select_player">selectPlayer:</string>
I don't see you use this value at all. You can remove it.

2018-05-17 00:11 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/res/values/strings.xml
> +       <string name="open">Open</string>
I don't see you use this value at all. You can remove it.

2018-05-17 04:01 UTC, sndy35 commented
Implemented the review comments. Please review

2018-05-31 18:23 UTC, brol1dev requested changes
Added more comments. That should be all that is remaining.

2018-05-31 18:23 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/lists/ContentProtectionListActivity.java
> +   // selectionMap.put("Ooyala Player Token", new PlayerSelectionOption("0yMjJ2ZDosUnthiqqIM3c8Eb8Ilx5r52", "c0cTkxOqALQviQIGAHWY5hP0q9gU", "http://www.ooyala.com", OoyalaPlayerTokenPlayerActivity.cl
why did you comment this asset? This is the only one we have in here. Please add it back.

2018-05-31 18:23 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/players/CustomActivity.java
> +      embedCodeEditText = (EditText) findViewById(R.id.embed_edit_text);
It is now redundant to cast the type of the object when using `findViewById` you can remove the casting type now

2018-05-31 18:23 UTC, rcvrgs commented on ContentProtectionSampleApp/app/src/main/java/com/ooyala/sample/players/CustomActivity.java
> +        return "Custom Activity";
Use another name here. My suggestion is: `Asset Options`

2018-05-31 18:23 UTC, rcvrgs commented on ContentProtectionSampleApp/app/build.gradle
> +
there's still extra space here.

2018-06-07 18:52 UTC, brol1dev approved these changes
LGTM

2018-06-07 18:53 UTC, rcvrgs commented
@akshaydch11 can you review this one too? You can merge if you're ok with it.

2018-06-08 19:53 UTC, merged