New Activity for DTOSampleApp Automation
ooyala/android-sample-apps pull request #344
Opened 2018-06-25 15:25 UTC by ramanamca04

New Activity created for DTOSampleApp Automation, that allows to input EmbedCd, Pcode, ApiKey and SecretKey from SampleApp.

2018-07-18 23:05 UTC, akshaydch11 requested changes
Please remove "added by rmanchi" comments from everywhere.

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/players/OoyalaSkinOPTPlayerActivity.java
> +//added below two imports by rmanchi
remove this comment

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/players/OoyalaSkinOPTPlayerActivity.java
> +  //Changed by rmanchi - Removed final keyword for apikey, secret & account_id
remove this comment

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/players/OoyalaSkinOPTPlayerActivity.java
> +    //added by rmanchi
remove this comment

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/utils/PlayerSelectionOption.java
> +  //added by rmanchi
remove comment

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/utils/PlayerSelectionOption.java
> +    //added by rmanchi
remove comment

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/utils/PlayerSelectionOption.java
> +  //added by rmanchi
remove comment

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/utils/PlayerSelectionOption.java
> +  //added by rmanchi
remove comment

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/utils/PlayerSelectionOption.java
> +  //added by rmanchi
remove comment

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/players/OoyalaSkinOPTPlayerActivity.java
> +    //added by rmanchi
remove comment

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/players/OoyalaSkinOPTPlayerActivity.java
> +    //added by rmanchi
remove comment

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/players/OoyalaSkinOPTPlayerActivity.java
> +  //added below two stmts by rmanchi
remove comment

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/lists/BasicPlaybackListActivity.java
> +    //added by rmanchi - IF condition
remove comment

2018-07-18 23:05 UTC, akshaydch11 commented on PlaybackLab/DownloadToOwnSampleApp/app/src/main/java/com/ooyala/sample/complete/MainExoPlayerActivity.java
> +    //Added by rmanchi
remove comment

2018-07-23 09:16 UTC, ramanamca04 commented
@akshaydch11  Worked on review comments given by you. Could you please verify. Thanks!

2018-10-22 22:43 UTC, brol1dev approved these changes
LGTM

2018-10-22 22:46 UTC, akshaydch11 commented
@ramanamca04  Please resolve conflicts and update PR.

2018-10-25 13:40 UTC, closed without merging