PLAYER-5676 [Android] Sample apps refactoring
ooyala/android-sample-apps pull request #491
Opened 2019-07-02 14:40 UTC by SergeyBicarte

Updated various sample apps:
- corrected life cycle calls
- added destroy and release resources for player and his skin controllers

2019-07-02 14:53 UTC, AlinaVoronkovaEpam commented
LGTM, going to fix incorrect Android Studio indents

2019-07-02 14:53 UTC, AlinaVoronkovaEpam requested changes
let's fix indents

2019-07-05 15:50 UTC, AlinaVoronkovaEpam approved these changes

2019-07-08 08:38 UTC, maxkupetskii approved these changes

2019-07-08 08:38 UTC, merged